import React from "react";
import { Image,StyleSheet,Text,View } from "react-native";


const Scale=()=>{
    return(
        <View style={Styles.container}>
                <Text>Hello Scaling this is React native Size matters</Text>
                <Image style={Styles.img} resizeMode="contain" source={require('./src2/images/Party.jpeg')}/>
            <Text  style={Styles.text}>{"Lorem this is a text that has been generated by me to check that Lorem this is a text that has been generated by me to check that Lorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check thatLorem this is a text that has been generated by me to check that"}</Text>
        </View>
    )
}
export default Scale;
const Styles = StyleSheet.create({
    img:{
        height:300,
        width:600,
        marginTop:40
        

    },
    container:{
        flex:1,
        flexDirection:'column',
        backgroundColor:'white',
     

    },
    text:{
        fontSize:24
        // color:"white",
    }
})